# Development environment
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: video-downloader-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
      - downloads:/app/downloads
    command: npm run start:dev
    restart: unless-stopped
    networks:
      - video-downloader-network

volumes:
  downloads:
    driver: local

networks:
  video-downloader-network:
    driver: bridge
